[package]
edition = "2021"
name = "impact"
version = "0.0.1"

[dependencies]
lambda_runtime = "0.13.0"
lazy_static = "1.5.0"
serde = "1.0.209"
serde_json = "1.0.127"
tokio = { version = "1.39.3", features = ["macros"] }

[dev-dependencies]
tokio-test = "0.4.4"
