name: Validate Pull Request

on:
    pull_request:
        branches:
            - develop
            - prod

jobs:
    validate:
        name: Validate Pull Request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Cargo
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                components: rustfmt

            - name: Cargo Build
              run: |
                cargo build

            - name: Rust Format
              uses: actions-rust-lang/rustfmt@v1

            - name: Cargo Test
              run: |
                cargo test --all-fatures